name: LaTeX

on: push

jobs:
  pdfLaTeX:
    runs-on: ubuntu-latest
    container:
    #   image: ghcr.io/viluon/cv:slim
      image: texlive/texlive:latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: compile
      run: |
        latexmk -pdf -file-line-error cv.tex

    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pdfs
        path: '*.pdf'

    - name: release
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        # GitHub secret token
        repo_token: ${{ github.token }}
        # Git tag (for automatic releases)
        automatic_release_tag: latest
        # Should this release be marked as a draft?
        prerelease: false
        # Release title (for automatic releases)
        title: curriculum vitae
        # Assets to upload to the release
        files: |
          cv.pdf
